---
abstract: 'It is a simple history file maker. '
author:
  - 'Kazuhiro Nishikawa <kazuhiro.nishikawa@gmail.com>'
build_requires:
  Path::Class: 0
  Path::Class::Dir: 0
  Path::Class::Entity: 0
  Path::Class::File: 0
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-History
no_index:
  directory:
    - inc
    - t
requires:
  Class::Accessor::Fast: 0
  File::ReadBackwards: 0
  IO::File: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.00002
